---
active_layers: [0,1,2,3,4,5,6,7,8,9,10,11]
num_layers: 12
num_bs_antennas: 32
num_rsrc_blocks: 100
block_size: 12 # Subcarriers per resource block
num_subcarriers: 1200 # Number of subcarriers per symbol
